// Type declarations for Prisma Client
// These are placeholder types - actual types are generated by Prisma

declare module '../../prisma/client' {
  import { PrismaClient } from '@prisma/client';
  
  export const db: PrismaClient;
}
