/**
 * Generator Handler - Code Generation Endpoint
 * @module mcp-server/handlers/generator
 * @description MCP handler for generating CSS/component code
 */

import { MCPTool } from '../index';
import { createSuccessResponse, createErrorResponse } from '../utils/response-formatter';

/** Generation request types */
type GenerationType = 
  | 'css-from-description'
  | 'tailwind-from-css'
  | 'component-from-spec'
  | 'utility-classes';

/** Generation options */
interface GenerationOptions {
  targetFramework?: 'css' | 'tailwind' | 'styled-components' | 'css-modules';
  includePrefixes?: boolean;
  includeComments?: boolean;
  minify?: boolean;
  accessibilityLevel?: 'none' | 'aa' | 'aaa';
}

/** Validation result */
interface ValidationResult {
  valid: boolean;
  errors: Array<{ line?: number; message: string; severity: 'error' | 'warning' }>;
  warnings: string[];
  suggestions: string[];
}

/**
 * Generate CSS from natural language description
 */
async function generateCSSFromDescription(
  description: string,
  options?: GenerationOptions
): Promise<{ css: string; explanation: string }> {
  // This would connect to AI service in production
  // For now, return template-based generation
  
  const framework = options?.targetFramework || 'css';
  const comments = options?.includeComments !== false;
  
  let css = '';
  let explanation = '';
  
  // Simple pattern matching for common requests
  const lowerDesc = description.toLowerCase();
  
  if (lowerDesc.includes('button') && (lowerDesc.includes('gradient') || lowerDesc.includes('colorful'))) {
    css = comments ? `/* Gradient Button - Generated by ROYCSS */\n` : '';
    css += `.gradient-btn {\n`;
    css += `  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n`;
    css += `  color: white;\n`;
    css += `  padding: 12px 24px;\n`;
    css += `  border: none;\n`;
    css += `  border-radius: 8px;\n`;
    css += `  font-weight: 600;\n`;
    css += `  cursor: pointer;\n`;
    css += `  transition: transform 0.2s, box-shadow 0.2s;\n`;
    css += `}\n\n`;
    css += `.gradient-btn:hover {\n`;
    css += `  transform: translateY(-2px);\n`;
    css += `  box-shadow: 0 4px 15px rgba(102, 126, 234, 0.4);\n`;
    css += `}\n`;
    
    if (framework === 'tailwind') {
      css = `class="bg-gradient-to-r from-indigo-500 to-purple-600 text-white px-6 py-3 rounded-lg font-semibold hover:-translate-y-0.5 hover:shadow-lg transition-all duration-200"`;
    }
    
    explanation = 'Created a gradient button with hover lift effect. Uses modern gradient syntax with smooth transitions.';
  } else if (lowerDesc.includes('card') && (lowerDesc.includes('shadow') || lowerDesc.includes('elevation'))) {
    css = comments ? `/* Elevated Card - Generated by ROYCSS */\n` : '';
    css += `.elevated-card {\n`;
    css += `  background: white;\n`;
    css += `  border-radius: 16px;\n`;
    css += `  padding: 24px;\n`;
    css += `  box-shadow:\n`;
    css += `    0 4px 6px -1px rgba(0, 0, 0, 0.1),\n`;
    css += `    0 2px 4px -2px rgba(0, 0, 0, 0.1);\n`;
    css += `  transition: box-shadow 0.3s, transform 0.3s;\n`;
    css += `}\n\n`;
    css += `.elevated-card:hover {\n`;
    css += `  box-shadow:\n`;
    css += `    0 20px 25px -5px rgba(0, 0, 0, 0.1),\n`;
    css += `    0 8px 10px -6px rgba(0, 0, 0, 0.1);\n`;
    css += `  transform: translateY(-4px);\n`;
    css += `}\n`;
    
    if (framework === 'tailwind') {
      css = `class="bg-white rounded-2xl p-6 shadow shadow-md hover:shadow-xl hover:-translate-y-1 transition-all duration-300"`;
    }
    
    explanation = 'Created an elevated card with layered shadows for depth. Hover increases elevation.';
  } else {
    // Default generic response
    css = comments ? `/* Generated by ROYCSS based on: "${description}" */\n` : '';
    css += `.generated-element {\n`;
    css += `  /* Customize these styles */\n`;
    css += `  display: flex;\n`;
    css += `  align-items: center;\n`;
    css += `  justify-content: center;\n`;
    css += `  padding: 16px;\n`;
    css += `  border-radius: 8px;\n`;
    css += `  transition: all 0.3s ease;\n`;
    css += `}\n`;
    
    explanation = `Generated base styles for: ${description}. Customize the properties to match your requirements.`;
  }
  
  return { css, explanation };
}

/**
 * Convert CSS to Tailwind classes
 */
function convertCSSToTailwind(css: string): { classes: string; notes: string[] } {
  const notes: string[] = [];
  const classes: string[] = [];
  
  // Simple conversion mappings
  const conversions: Array<[RegExp, string]> = [
    [/display:\s*flex/, 'flex'],
    [/justify-content:\s*center/, 'justify-center'],
    [/align-items:\s*center/, 'items-center'],
    [/display:\s*grid/, 'grid'],
    [/display:\s*block/, 'block'],
    [/display:\s*inline-block/, 'inline-block'],
    [/display:\s*hidden|display:\s*none/, 'hidden'],
    [/position:\s*relative/, 'relative'],
    [/position:\s*absolute/, 'absolute'],
    [/position:\s*fixed/, 'fixed'],
    [/position:\s*sticky/, 'sticky'],
    [/padding:\s*(\d+)px/, (_m, p) => `p-${Math.round(p / 4)}`],
    [/margin:\s*(\d+)px/, (_m, m) => `m-${Math.round(m / 4)}`],
    [/padding-top:\s*(\d+)px/, (_m, p) => `pt-${Math.round(p / 4)}`],
    [/padding-bottom:\s*(\d+)px/, (_m, p) => `pb-${Math.round(p / 4)}`],
    [/padding-left:\s*(\d+)px/, (_m, p) => `pl-${Math.round(p / 4)}`],
    [/padding-right:\s*(\d+)px/, (_m, p) => `pr-${Math.round(p / 4)}`],
    [/margin-top:\s*(\d+)px/, (_m, m) => `mt-${Math.round(m / 4)}`],
    [/margin-bottom:\s*(\d+)px/, (_m, m) => `mb-${Math.round(m / 4)}`],
    [/margin-left:\s*(\d+)px/, (_m, m) => `ml-${Math.round(m / 4)}`],
    [/margin-right:\s*(\d+)px/, (_m, m) => `mr-${Math.round(m / 4)}`],
    [/text-align:\s*center/, 'text-center'],
    [/text-align:\s*left/, 'text-left'],
    [/text-align:\s*right/, 'text-right'],
    [/font-weight:\s*bold|font-weight:\s*700/, 'font-bold'],
    [/font-weight:\s*(\d+)/, (_m, w) => `font-[${w}]`],
    [/font-size:\s*(\d+)px/, (_m, s) => `text-[${s}px]`],
    [/color:\s*white|#fff/i, 'text-white'],
    [/color:\s*black|#000/i, 'text-black'],
    [/background:\s*white|#fff/i, 'bg-white'],
    [/background:\s*black|#000/i, 'bg-black'],
    [/border-radius:\s*(\d+)px/, (_m, r) => `rounded-[${r}px]`],
    [/overflow:\s*hidden/, 'overflow-hidden'],
    [/overflow:\s*auto/, 'overflow-auto'],
    [/cursor:\s*pointer/, 'cursor-pointer'],
    [/width:\s*100%/i, 'w-full'],
    [/height:\s*100%/i, 'h-full'],
    [/opacity:\s*0/, 'opacity-0'],
    [/opacity:\s*50|%?50/, 'opacity-50'],
    [/opacity:\s*100|%?100/, 'opacity-100'],
    [/z-index:\s*10/, 'z-10'],
    [/z-index:\s*20/, 'z-20'],
    [/z-index:\s*50/, 'z-50'],
    [/gap:\s*(\d+)px/, (_m, g) => `gap-${Math.round(g / 4)}`],
    [/flex-direction:\s*column/, 'flex-col'],
    [/flex-direction:\s*row/, 'flex-row'],
    [/flex-wrap:\s*wrap/, 'flex-wrap'],
  ];
  
  // Apply conversions
  for (const [pattern, replacement] of conversions) {
    if (pattern.test(css)) {
      if (typeof replacement === 'function') {
        const match = css.match(pattern);
        classes.push(replacement(match as RegExpExecArray));
      } else {
        classes.push(replacement);
      }
    }
  }
  
  // Check for unsupported properties
  if (/animation|keyframes|transform/.test(css)) {
    notes.push('Animations and transforms may need custom CSS');
  }
  if (/::before|::after|:hover|:focus/.test(css)) {
    notes.push('Pseudo-elements and pseudo-states need custom CSS');
  }
  if (/box-shadow.*\(.*\)/.test(css)) {
    notes.push('Complex box-shadows may need custom values');
  }
  if (/linear-gradient|radial-gradient/.test(css)) {
    notes.push('Gradients can be converted to Tailwind utility classes');
  }
  
  return {
    classes: classes.join(' ') || '/* Manual conversion needed */',
    notes
  };
}

/**
 * Validate CSS code
 */
function validateCSS(css: string): ValidationResult {
  const errors: ValidationResult['errors'] = [];
  const warnings: string[] = [];
  const suggestions: string[] = [];
  
  // Basic validation checks
  const lines = css.split('\n');
  
  lines.forEach((line, index) => {
    const trimmed = line.trim();
    
    // Check for common issues
    if (trimmed && !trimmed.endsWith('{') && !trimmed.endsWith('}') && !trimmed.endsWith(';') && !trimmed.endsWith(',')) {
      if (trimmed.includes(':') && !trimmed.startsWith('//') && !trimmed.startsWith('/*')) {
        warnings.push(`Line ${index + 1}: Missing semicolon might cause issues`);
      }
    }
    
    // Check for deprecated properties
    if (trimmed.includes('-moz-') || trimmed.includes('-webkit-') || trimmed.includes('-ms-')) {
      suggestions.push(`Line ${index + 1}: Consider if vendor prefix is still needed`);
    }
    
    // Check for !important
    if (trimmed.includes('!important')) {
      warnings.push(`Line ${index + 1}: Avoid !important when possible`);
      suggestions.push('Use more specific selectors instead');
    }
  });
  
  // Check for balanced braces
  const openBraces = (css.match(/{/g) || []).length;
  const closeBraces = (css.match(/}/g) || []).length;
  
  if (openBraces !== closeBraces) {
    errors.push({
      message: `Unbalanced braces: ${openBraces} opening, ${closeBraces} closing`,
      severity: 'error'
    });
  }
  
  // Check for balanced parentheses
  const openParens = (css.match(/\(/g) || []).length;
  const closeParens = (css.match(/\)/g) || []).length;
  
  if (openParens !== closeParens) {
    errors.push({
      message: `Unbalanced parentheses: ${openParens} opening, ${closeParens} closing`,
      severity: 'error'
    });
  }
  
  // Suggestions
  if (!css.includes('box-sizing')) {
    suggestions.push('Consider adding box-sizing: border-box globally');
  }
  
  if (css.includes('px') && !css.includes('rem') && !css.includes('em')) {
    suggestions.push('Consider using rem/em units for better scalability');
  }
  
  if (!css.includes('@media') && css.length > 200) {
    suggestions.push('Consider adding responsive breakpoints');
  }
  
  return {
    valid: errors.length === 0,
    errors,
    warnings,
    suggestions
  };
}

/** Export MCP tools for generator */
export const generatorTools: MCPTool[] = [
  {
    name: 'generate_css',
    description: 'Generate CSS from natural language description',
    inputSchema: {
      type: 'object',
      properties: {
        description: {
          type: 'string',
          description: 'Natural language description of desired CSS'
        },
        targetFramework: {
          type: 'string',
          enum: ['css', 'tailwind', 'styled-components', 'css-modules'],
          description: 'Target output format'
        },
        includeComments: {
          type: 'boolean',
          description: 'Include explanatory comments'
        }
      },
      required: ['description']
    },
    handler: async (params) => {
      const result = await generateCSSFromDescription(
        params.description as string,
        params as GenerationOptions
      );
      return createSuccessResponse(result);
    }
  },
  {
    name: 'convert_to_tailwind',
    description: 'Convert CSS to Tailwind CSS classes',
    inputSchema: {
      type: 'object',
      properties: {
        css: {
          type: 'string',
          description: 'CSS code to convert'
        }
      },
      required: ['css']
    },
    handler: async (params) => {
      const result = convertCSSToTailwind(params.css as string);
      return createSuccessResponse(result);
    }
  },
  {
    name: 'validate_css',
    description: 'Validate CSS code for errors and best practices',
    inputSchema: {
      type: 'object',
      properties: {
        css: {
          type: 'string',
          description: 'CSS code to validate'
        }
      },
      required: ['css']
    },
    handler: async (params) => {
      const result = validateCSS(params.css as string);
      return createSuccessResponse(result);
    }
  }
];

export default {
  generateCSSFromDescription,
  convertCSSToTailwind,
  validateCSS,
  generatorTools
};
