/**
 * Init Command
 * @module roycss-cli/commands/init
 * @description Initialize ROYCSS in a new project
 */

import { Command } from 'commander';
import fs from 'fs-extra';
import path from 'path';
import { logger, createSpinner } from '../utils/logger';
import { ConfigManager, DEFAULT_CONFIG } from '../utils/config';

/** Init options */
interface InitOptions {
  force?: boolean;
  type?: 'full' | 'minimal' | 'tailwind';
  dir?: string;
}

/** Project structure for full install */
const FULL_PROJECT_STRUCTURE = {
  'src/styles/roycss/': {
    '_effects.css': `/* ROYCSS Effects */
/* Generated by: roycss init */

/* Import individual effects as needed */
/* @import './effects/bounce.css'; */
/* @import './effects/fade-in.css'; */

/* Or import all effects */
/* @import './effects/all.css';`,
    'effects/': {
      '_bounce.css': `/* Bounce Effect - ROYCSS */
.roy-bounce {
  animation: roy-bounce 0.6s ease-in-out;
}

@keyframes roy-bounce {
  0%, 100% { transform: translateY(0); }
  50% { transform: translateY(-10px); }
}`,
      '_fade-in.css': `/* Fade In Effect - ROYCSS */
.roy-fade-in {
  opacity: 0;
  animation: roy-fade-in 0.5s ease-out forwards;
}

@keyframes roy-fade-in {
  to { opacity: 1; }
}`,
      '_pulse.css': `/* Pulse Effect - ROYCSS */
.roy-pulse {
  animation: roy-pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite;
}

@keyframes roy-pulse {
  0%, 100% { opacity: 1; }
  50% { opacity: 0.5; }
}`
    },
    '_components.css': `/* ROYCSS Components */
/* Import components as needed */`,
    '_utilities.css': `/* ROYCSS Utilities */
/* Utility classes and mixins */`
  }
};

/** Minimal project structure */
const MINIMAL_PROJECT_STRUCTURE = {
  'src/styles/roycss/': {
    'index.css': `/* ROYCSS - Minimal Setup */
/* Add effects and components as needed */`
  }
};

/**
 * Create directory structure recursively
 */
async function createStructure(
  basePath: string,
  structure: Record<string, any>,
  spinner?: ReturnType<typeof createSpinner>
): Promise<void> {
  for (const [name, content] of Object.entries(structure)) {
    const fullPath = path.join(basePath, name);
    
    if (typeof content === 'object' && !content.toString().startsWith('/*')) {
      // It's a directory
      await fs.ensureDir(fullPath);
      await createStructure(fullPath, content, spinner);
    } else {
      // It's a file
      await fs.writeFile(fullPath, content || '');
      spinner?.update(`Created ${name}`);
    }
  }
}

/**
 * Execute init command
 */
export async function executeInit(options: InitOptions): Promise<void> {
  const targetDir = options.dir || process.cwd();
  
  // Check if already initialized
  const configPath = path.join(targetDir, '.roycssrc.json');
  
  if (fs.existsSync(configPath) && !options.force) {
    logger.warning('ROYCSS is already initialized in this directory.');
    logger.info('Use --force to reinitialize.');
    return;
  }

  const spinner = createSpinner({
    text: 'Initializing ROYCSS...',
    successText: 'ROYCSS initialized successfully!'
  });

  try {
    // Determine structure based on type
    const structureType = options.type || 'full';
    const structure = structureType === 'full' 
      ? FULL_PROJECT_STRUCTURE 
      : structureType === 'tailwind'
        ? { 'src/styles/roycss/': { 'tailwind.css': `/* ROYCSS Tailwind Utilities */` } }
        : MINIMAL_PROJECT_STRUCTURE;

    // Create directory structure
    await createStructure(targetDir, structure, spinner);

    // Create config file
    const configManager = new ConfigManager(targetDir);
    configManager.save({
      ...DEFAULT_CONFIG,
      version: 1,
      outputFormat: structureType === 'tailwind' ? 'tailwind' : 'css'
    });

    spinner.succeed();

    // Print summary
    logger.blank();
    logger.success(`Project initialized with ${structureType} setup`);
    logger.info(`Config file: ${configPath}`);
    logger.info('');
    logger.info('Next steps:');
    logger.info('  • Import styles in your main CSS file');
    logger.info('  • Run "roycss add <effect>" to add effects');
    logger.info('  • Run "roycss search <query>" to find effects');
    
  } catch (error) {
    spinner.fail(error instanceof Error ? error.message : 'Initialization failed');
    throw error;
  }
}

/** Export command for Commander */
export const initCommand = new Command('init')
  .description('Initialize ROYCSS in a new project')
  .option('-f, --force', 'Force reinitialization', false)
  .option('-t, --type <type>', 'Setup type (full, minimal, tailwind)', 'full')
  .option('-d, --dir <path>', 'Target directory')
  .action(executeInit);

export default executeInit;
