/**
 * Response Formatter Service
 * @module roycss/ai/services/response-formatter
 * @description Format and validate AI responses
 */

import {
  AIResponse,
  GeneratedCSS,
  CSSExplanation,
  ImprovementSuggestions,
  AccessibilityReport,
  TailwindClasses,
  AIResponseData
} from '../types';

/** Formatting options */
export interface FormatOptions {
  includeMetadata?: boolean;
  prettyPrint?: boolean;
  includeCodeBlocks?: boolean;
  language?: string;
}

/**
 * Response Formatter Class
 */
export class ResponseFormatter {
  /**
   * Format any AI response for display
   */
  static formatResponse(response: AIResponse, options: FormatOptions = {}): string {
    if (!response.success) {
      return this.formatError(response);
    }

    const data = response.data;
    if (!data) {
      return 'No data in response';
    }

    // Detect response type and format accordingly
    if (typeof data === 'object' && 'content' in data) {
      // Raw chat response
      return options.includeCodeBlocks
        ? this.formatAsMarkdown(String(data.content))
        : String(data.content);
    }

    if (typeof data === 'object' && 'css' in data) {
      return this.formatGeneratedCSS(data as unknown as GeneratedCSS, options);
    }

    if (typeof data === 'object' && 'summary' in data) {
      return this.formatExplanation(data as unknown as CSSExplanation, options);
    }

    if (typeof data === 'object' && 'improvedCode' in data) {
      return this.formatImprovements(data as unknown as ImprovementSuggestions, options);
    }

    if (typeof data === 'object' && 'overallScore' in data) {
      return this.formatAccessibilityReport(data as unknown as AccessibilityReport, options);
    }

    if (typeof data === 'object' && 'classes' in data) {
      return this.formatTailwindClasses(data as unknown as TailwindClasses, options);
    }

    // Default: stringify
    return options.prettyPrint
      ? JSON.stringify(data, null, 2)
      : JSON.stringify(data);
  }

  /**
   * Format error response
   */
  private static formatError(response: AIResponse): string {
    const error = response.error;
    if (!error) {
      return 'An unknown error occurred';
    }

    let message = `**Error: ${error.code}**\n\n${error.message}`;
    
    if (error.retryable) {
      message += '\n\n*This error can be retried.*';
    }

    if (error.details) {
      message += `\n\nDetails: ${JSON.stringify(error.details, null, 2)}`;
    }

    return message;
  }

  /**
   * Format generated CSS response
   */
  static formatGeneratedCSS(data: GeneratedCSS, options: FormatOptions = {}): string {
    let output = '';

    if (options.prettyPrint) {
      output += '## Generated CSS ✨\n\n';
    }

    // CSS Code
    if (options.includeCodeBlocks !== false) {
      output += '```css\n' + data.css + '\n```\n\n';
    } else {
      output += data.css + '\n\n';
    }

    // HTML Example
    if (data.html) {
      output += '**Example HTML:**\n';
      output += '```html\n' + data.html + '\n```\n\n';
    }

    // Classes documentation
    if (data.classes && Object.keys(data.classes).length > 0) {
      output += '**Classes:**\n\n';
      for (const [name, desc] of Object.entries(data.classes)) {
        output += `- \`${name}\`: ${desc}\n`;
      }
      output += '\n';
    }

    // Dependencies
    if (data.dependencies && data.dependencies.length > 0) {
      output += '**Dependencies:**\n';
      for (const dep of data.dependencies) {
        output += `- ${dep}\n`;
      }
    }

    // Metadata
    if (options.includeMetadata) {
      output += '\n---\n*Generated by RoyAI*';
    }

    return output;
  }

  /**
   * Format CSS explanation
   */
  static formatExplanation(data: CSSExplanation, options: FormatOptions = {}): string {
    let output = '';

    if (options.prettyPrint) {
      output += '## CSS Explanation 📚\n\n';
    }

    // Summary
    output += `**Summary:** ${data.summary}\n\n`;

    // Properties
    if (data.properties && data.properties.length > 0) {
      output += '**Properties:**\n\n';
      for (const prop of data.properties) {
        output += `### \`${prop.property}: ${prop.value}\`\n\n`;
        output += `${prop.explanation}\n\n`;
        
        if (prop.browserSupport) {
          output += `*Browser Support: ${prop.browserSupport}*\n\n`;
        }
        
        if (prop.alternatives && prop.alternatives.length > 0) {
          output += `Alternatives: ${prop.alternatives.map(a => `\`${a}\``).join(', ')}\n\n`;
        }
      }
    }

    // Tips
    if (data.tips && data.tips.length > 0) {
      output += '**Tips:**\n';
      for (const tip of data.tips) {
        output += `- 💡 ${tip}\n`;
      }
    }

    // Related concepts
    if (data.relatedConcepts && data.relatedConcepts.length > 0) {
      output += '\n**Related Concepts:**\n';
      for (const concept of data.relatedConcepts) {
        output += `- ${concept}\n`;
      }
    }

    return output;
  }

  /**
   * Format improvement suggestions
   */
  static formatImprovements(data: ImprovementSuggestions, options: FormatOptions = {}): string {
    let output = '';

    if (options.prettyPrint) {
      output += '## Improvement Suggestions 🚀\n\n';
    }

    // Overall score
    output += `**Overall Score:** ${data.overallScore}/100\n\n`;

    // Category scores
    output += '| Category | Score |\n|----------|-------|\n';
    output += `| Performance | ${data.scores.performance}/100 |\n`;
    output += `| Accessibility | ${data.scores.accessibility}/100 |\n`;
    output += `| Maintainability | ${data.scores.maintainability}/100 |\n`;
    output += `| Browser Compatibility | ${data.scores.browserCompatibility}/100 |\n\n`;

    // Changes
    if (data.changes && data.changes.length > 0) {
      output += '**Changes Made:**\n\n';
      for (const change of data.changes) {
        const icon = this.getChangeIcon(change.type);
        const impactIcon = this.getImpactIcon(change.impact);
        output += `${icon} **[${change.type.toUpperCase()}]** ${change.description} ${impactIcon}\n`;
        output += `   *Category: ${change.category}*\n\n`;
      }
    }

    // Improved code
    if (data.improvedCode) {
      output += '**Improved Code:**\n';
      output += '```css\n' + data.improvedCode + '\n```\n';
    }

    return output;
  }

  /**
   * Format accessibility report
   */
  static formatAccessibilityReport(data: AccessibilityReport, options: FormatOptions = {}): string {
    let output = '';

    if (options.prettyPrint) {
      output += '## Accessibility Report ♿\n\n';
    }

    // Overall score and compliance
    const complianceEmoji = data.complianceLevel === 'pass' ? '✅' : 
                           data.complianceLevel === 'partial' ? '⚠️' : '❌';
    output += `${complianceEmoji} **Score:** ${data.overallScore}/100 (${data.complianceLevel.toUpperCase()})\n\n`;

    // Issues
    if (data.issues && data.issues.length > 0) {
      output += '**Issues Found:**\n\n';
      
      const errors = data.issues.filter(i => i.severity === 'error');
      const warnings = data.issues.filter(i => i.severity === 'warning');
      const infos = data.issues.filter(i => i.severity === 'info');

      if (errors.length > 0) {
        output += `### Errors (${errors.length})\n`;
        for (const issue of errors) {
          output += `- ❌ **${issue.category}:** ${issue.description}`;
          if (issue.wcagCriterion) output += ` [${issue.wcagCriterion}]`;
          output += '\n';
          if (issue.fix) output += `  *Fix: ${issue.fix}*\n`;
        }
        output += '\n';
      }

      if (warnings.length > 0) {
        output += `### Warnings (${warnings.length})\n`;
        for (const issue of warnings) {
          output += `- ⚠️ **${issue.category}:** ${issue.description}\n`;
        }
        output += '\n';
      }

      if (infos.length > 0) {
        output += `### Info (${infos.length})\n`;
        for (const issue of infos) {
          output += `- ℹ️ **${issue.category}:** ${issue.description}\n`;
        }
        output += '\n';
      }
    } else {
      output += '**No issues found!** 🎉\n\n';
    }

    // Recommendations
    if (data.recommendations && data.recommendations.length > 0) {
      output += '**Recommendations:**\n';
      for (const rec of data.recommendations) {
        output += `- ${rec}\n`;
      }
    }

    return output;
  }

  /**
   * Format Tailwind classes
   */
  static formatTailwindClasses(data: TailwindClasses, options: FormatOptions = {}): string {
    let output = '';

    if (options.prettyPrint) {
      output += '## Tailwind Classes 🎨\n\n';
    }

    // Main classes
    output += '**Classes:**\n';
    output += '```html\nclass="' + data.classes + '"\n```\n\n';

    // Custom CSS needed
    if (data.customCss) {
      output += '**Additional CSS Required:**\n';
      output += '```css\n' + data.customCss + '\n```\n\n';
    }

    // HTML Example
    if (data.htmlExample) {
      output += '**HTML Example:**\n';
      output += '```html\n' + data.htmlExample + '\n```\n\n';
    }

    // Notes
    if (data.notes && data.notes.length > 0) {
      output += '**Notes:**\n';
      for (const note of data.notes) {
        output += `- ${note}\n`;
      }
    }

    return output;
  }

  /**
   * Format as markdown
   */
  static formatAsMarkdown(content: string): string {
    // If already contains markdown formatting, return as-is
    if (content.includes('```') || content.includes('#') || content.includes('**')) {
      return content;
    }

    // Try to detect and format JSON
    try {
      const parsed = JSON.parse(content);
      return '```json\n' + JSON.stringify(parsed, null, 2) + '\n```';
    } catch {
      // Return as plain text in code block if it looks like code
      if (content.includes('{') || content.includes(';') || content.includes(':')) {
        return '```\n' + content + '\n```';
      }
      return content;
    }
  }

  /**
   * Validate response structure
   */
  static validateResponse(response: AIResponse): { valid: boolean; errors: string[] } {
    const errors: string[] = [];

    if (typeof response.success !== 'boolean') {
      errors.push('Missing or invalid success field');
    }

    if (!response.requestId) {
      errors.push('Missing requestId');
    }

    if (!(response.timestamp instanceof Date) && typeof response.timestamp !== 'string') {
      errors.push('Invalid timestamp');
    }

    if (response.success && !response.data) {
      errors.push('Success response missing data');
    }

    if (!response.success && !response.error) {
      errors.push('Error response missing error details');
    }

    return {
      valid: errors.length === 0,
      errors
    };
  }

  /**
   * Extract code from response
   */
  static extractCode(response: AIResponse): string | null {
    if (!response.success || !response.data) return null;

    const data = response.data as Record<string, unknown>;
    
    if (typeof data.css === 'string') return data.css;
    if (typeof data.content === 'string') return data.content;
    if (typeof data.code === 'string') return data.code;
    if (typeof data.improvedCode === 'string') return data.improvedCode;
    if (typeof data.classes === 'string') return data.classes;

    return null;
  }

  /**
   * Get icon for change type
   */
  private static getChangeIcon(type: string): string {
    switch (type) {
      case 'addition': return '➕';
      case 'modification': return '✏️';
      case 'removal': return '➖';
      case 'refactor': return '🔧';
      default: return '•';
    }
  }

  /**
   * Get icon for impact level
   */
  private static getImpactIcon(impact: string): string {
    switch (impact) {
      case 'high': return '🔴';
      case 'medium': return '🟡';
      case 'low': return '🟢';
      default: return '';
    }
  }
}

export default ResponseFormatter;
