/**
 * ROYCSS Export System - CodePen & External Platform Exports
 * @module roycss/export
 * @description Utilities for exporting components to external platforms like CodePen, CodeSandbox, etc.
 */

import type { ExportOptions, ExportResult } from '../types';

// ============================================================================
// Types
// ============================================================================

export interface ComponentExportData {
  /** Component name */
  name: string;
  /** HTML content */
  html: string;
  /** CSS content */
  css: string;
  /** JavaScript content */
  js: string;
  /** Dependencies (for npm packages) */
  dependencies?: Record<string, string>;
}

// ============================================================================
// CodePen Export
// ============================================================================

const CODEPEN_API_URL = 'https://codepen.io/pen/define';

/**
 * Generate CodePen payload from component data
 */
function generateCodePenPayload(
  data: ComponentExportData,
  options: ExportOptions
): Record<string, unknown> {
  const payload = {
    title: options.title,
    description: options.description,
    html: wrapHTML(data.html),
    css: wrapCSS(data.css),
    js: wrapJS(data.js),
    css_external: options.externalStyles?.join(';') || undefined,
    js_external: options.externalScripts?.join(';') || undefined,
    editors: '101', // Show all editors by default
    layout: 'left', // Editor layout
  };

  return payload;
}

/**
 * Wrap HTML with boilerplate
 */
function wrapHTML(html: string): string {
  return `<!-- Generated by ROYCSS Component System -->
<div class="roycss-demo">
  ${html}
</div>`;
}

/**
 * Wrap CSS with base styles
 */
function wrapCSS(css: string): string {
  return `/* Generated by ROYCSS Component System */
/* Base Styles */
* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
  line-height: 1.6;
  color: #111827;
  background-color: #ffffff;
  padding: 2rem;
}

.roycss-demo {
  max-width: 800px;
  margin: 0 auto;
}

/* Component Styles */
${css}`;
}

/**
 * Wrap JS with boilerplate
 */
function wrapJS(js: string): string {
  return `// Generated by ROYCSS Component System
document.addEventListener('DOMContentLoaded', function() {
  ${js}
});`;
}

/**
 * Export component to CodePen
 * Opens a new window/tab with the CodePen editor pre-filled with the component code.
 */
export async function exportToCodePen(
  data: ComponentExportData,
  options: ExportOptions
): Promise<ExportResult> {
  try {
    const payload = generateCodePenPayload(data, options);
    
    // Create form and submit to open in new window
    const form = document.createElement('form');
    form.method = 'POST';
    form.action = CODEPEN_API_URL;
    form.target = '_blank';

    const input = document.createElement('input');
    input.type = 'hidden';
    input.name = 'data';
    input.value = JSON.stringify(payload);

    form.appendChild(input);
    document.body.appendChild(form);
    form.submit();
    document.body.removeChild(form);

    return {
      success: true,
      url: `${CODEPEN_API_URL}?${encodeURIComponent(JSON.stringify(payload))}`,
      payload,
    };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Failed to export to CodePen',
    };
  }
}

/**
 * Generate CodePen embed URL for embedding the pen
 */
export function generateCodePenEmbedUrl(penId: string, options?: {
  height?: number;
  theme?: 'light' | 'dark' | 'default';
  editable?: boolean;
}): string {
  const height = options?.height || 400;
  const theme = options?.theme || 'default';
  const editable = options?.editable ? 'true' : 'false';

  return `https://codepen.io/embed/preview/${penId}?height=${height}&theme-id=${theme}&editable=${editable}`;
}

// ============================================================================
// CodeSandbox Export
// ============================================================================

/**
 * Generate CodeSandbox parameters URL
 */
export async function exportToCodeSandbox(
  data: ComponentExportData,
  options: ExportOptions
): Promise<ExportResult> {
  try {
    // Create a basic sandbox structure
    const sandboxFiles = {
      'index.html': `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${options.title}</title>
  <link rel="stylesheet" href="./styles.css">
</head>
<body>
  ${data.html}
  <script src="./script.js"></script>
</body>
</html>`,
      'styles.css': data.css,
      'script.js': data.js,
      'package.json': JSON.stringify(
        {
          name: options.title.toLowerCase().replace(/\s+/g, '-'),
          version: '1.0.0',
          description: options.description,
          main: 'script.js',
          scripts: {
            start: 'serve',
            build: 'echo "Build complete"',
          },
          dependencies: data.dependencies || {},
        },
        null,
        2
      ),
    };

    // Create sandbox URL (simplified - actual implementation would use API)
    const params = btoa(JSON.stringify({ files: sandboxFiles }));
    const url = `https://codesandbox.io/api/v1/sandboxes/define?parameters=${params}`;

    return {
      success: true,
      url,
      payload: { files: sandboxFiles },
    };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Failed to export to CodeSandbox',
    };
  }
}

// ============================================================================
// GitHub Gist Export
// ============================================================================

/**
 * Generate GitHub Gist content
 */
export async function exportToGitHubGist(
  data: ComponentExportData,
  options: ExportOptions
): Promise<ExportResult> {
  try {
    const gistContent = {
      description: `${options.title} - ${options.description}`,
      public: !options.isPrivate,
      files: {
        [`${options.title.toLowerCase().replace(/\s+/g, '-')}.html`]: {
          content: data.html,
        },
        [`${options.title.toLowerCase().replace(/\s+/g, '-')}.css`]: {
          content: data.css,
        },
        [`${options.title.toLowerCase().replace(/\s+/g, '-')}.js`]: {
          content: data.js,
        },
        'README.md': {
          content: `# ${options.title}\n\n${options.description}\n\n## Usage\n\nThis is a ROYSS component exported from the Digital Lending OS platform.\n\n## Files\n\n- \`*.html\` - HTML structure\n- \`*.css\` - Styling\n- \`*.js\` - JavaScript functionality`,
        },
      },
    };

    // Note: Actual Gist creation requires authentication via GitHub API
    // This returns the content that would be posted
    return {
      success: true,
      payload: gistContent,
    };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Failed to create GitHub Gist',
    };
  }
}

// ============================================================================
// HTML File Export
// ============================================================================

/**
 * Generate standalone HTML file
 */
export function generateStandaloneHTML(
  data: ComponentExportData,
  options: ExportOptions
): string {
  const externalStyles = (options.externalStyles || [])
    .map((s) => `<link rel="stylesheet" href="${s}" />`)
    .join('\n');

  const externalScripts = (options.externalScripts || [])
    .map((s) => `<script src="${s}"></script>`)
    .join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${options.title}</title>
  <meta name="description" content="${options.description}">
  ${externalStyles}
  <style>
/* ROYCSS Component Styles */
${data.css}
  </style>
</head>
<body>
  <!-- ${options.title} - Generated by ROYCSS -->
  ${data.html}

  ${externalScripts}
  <script>
// ROYCSS Component Script
${data.js}
  </script>
</body>
</html>`;
}

/**
 * Download as HTML file
 */
export function downloadAsHTML(
  data: ComponentExportData,
  options: ExportOptions
): void {
  const html = generateStandaloneHTML(data, options);
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);

  const link = document.createElement('a');
  link.href = url;
  link.download = `${options.title.toLowerCase().replace(/\s+/g, '-')}.html`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

// ============================================================================
// Share URL Generator
// ============================================================================

/**
 * Generate shareable URL with encoded component data
 */
export function generateShareURL(
  data: ComponentExportData,
  options: ExportOptions
): string {
  const payload = JSON.stringify({
    ...data,
    title: options.title,
    description: options.description,
  });

  // Encode for URL (in production, you'd use a proper shortening service)
  const encoded = btoa(payload);
  
  // Return a placeholder URL pattern
  return `https://roycss.dev/share?c=${encoded.slice(0, 100)}...`; // Truncated for demo
}

// ============================================================================
// Export Helpers
// ============================================================================

/**
 * Get export format based on target
 */
export function getExporter(format: ExportOptions['format']) {
  switch (format) {
    case 'codepen':
      return exportToCodePen;
    case 'codesandbox':
      return exportToCodeSandbox;
    case 'github-gist':
      return exportToGitHubGist;
    default:
      throw new Error(`Unsupported export format: ${format}`);
  }
}

/**
 * Quick export helper - auto-detect best method or download
 */
export async function quickExport(
  data: ComponentExportData,
  options: ExportOptions
): Promise<ExportResult> {
  if (typeof window !== 'undefined' && navigator.clipboard) {
    // Try clipboard first for easy sharing
    const html = generateStandaloneHTML(data, options);
    await navigator.clipboard.writeText(html);
    
    return {
      success: true,
      payload: { message: 'Copied to clipboard!' },
    };
  }

  // Fallback to download
  downloadAsHTML(data, options);
  return {
    success: true,
    payload: { message: 'Downloaded as HTML file' },
  };
}
