/**
 * RoyAI Service - AI Service Layer
 * @module roycss/ai/service
 * @description Mock AI service with interface for real API integration
 */

import {
  AIMessage,
  AIGeneratedEffect,
  AIRequest,
  AIResponse,
  GeneratedCSS,
  CSSExplanation,
  TailwindClasses
} from './types';

/** Service configuration */
export interface AIServiceConfig {
  /** Provider type */
  provider: 'mock' | 'openai' | 'anthropic' | 'local';
  /** API key for real providers */
  apiKey?: string;
  /** Model to use */
  model?: string;
  /** Base URL for custom endpoints */
  baseUrl?: string;
  /** Maximum tokens for generation */
  maxTokens?: number;
  /** Temperature for creativity */
  temperature?: number;
}

/** Default configuration */
const DEFAULT_CONFIG: AIServiceConfig = {
  provider: 'mock',
  maxTokens: 2000,
  temperature: 0.7
};

/**
 * Response formatter utilities
 */
export class ResponseFormatter {
  /**
   * Format CSS code block with syntax highlighting wrapper
   */
  static formatCSSCode(css: string): string {
    return `\`\`\`css\n${css.trim()}\n\`\`\``;
  }

  /**
   * Format explanation with markdown
   */
  static formatExplanation(explanation: string, tips?: string[]): string {
    let output = `## Explanation\n\n${explanation}`;
    
    if (tips && tips.length > 0) {
      output += '\n\n### Tips\n';
      tips.forEach((tip, i) => {
        output += `\n${i + 1}. ${tip}`;
      });
    }
    
    return output;
  }

  /**
   * Format complete response with metadata
   */
  static formatResponse(content: string, type: 'css' | 'explanation' | 'general'): string {
    const timestamp = new Date().toLocaleTimeString();
    
    switch (type) {
      case 'css':
        return `${content}\n\n---\n*Generated by RoyAI at ${timestamp}*`;
      
      case 'explanation':
        return `${content}\n\n---\n*Explained by RoyAI at ${timestamp}*`;
      
      default:
        return content;
    }
  }

  /**
   * Extract code blocks from response
   */
  static extractCodeBlocks(text: string): string[] {
    const regex = /```(?:css|scss|less|html)?\n([\s\S]*?)```/g;
    const codes: string[] = [];
    let match;
    
    while ((match = regex.exec(text)) !== null) {
      codes.push(match[1].trim());
    }
    
    return codes;
  }

  /**
   * Validate generated CSS
   */
  static validateCSS(css: string): { valid: boolean; errors: string[] } {
    const errors: string[] = [];
    
    // Check balanced braces
    const openBraces = (css.match(/{/g) || []).length;
    const closeBraces = (css.match(/}/g) || []).length;
    
    if (openBraces !== closeBraces) {
      errors.push(`Unbalanced braces: ${openBraces} opening, ${closeBraces} closing`);
    }
    
    // Check basic structure
    if (!css.includes('{') && !css.includes('}')) {
      errors.push('No valid CSS rule blocks found');
    }
    
    // Check for common issues
    if (/[^{]};\s*{/g.test(css)) {
      errors.push('Possible missing selector before declaration block');
    }
    
    return {
      valid: errors.length === 0,
      errors
    };
  }
}

/**
 * Mock response database for demo mode
 */
const MOCK_RESPONSES: Record<string, () => Promise<string>> = {
  'bounce': async () => `Here's a bouncing effect:\n\n${ResponseFormatter.formatCSSCode(`.bounce-effect {
  animation: bounce 0.6s ease-in-out infinite;
}

@keyframes bounce {
  0%, 100% {
    transform: translateY(0);
    animation-timing-function: cubic-bezier(0.8, 0, 1, 1);
  }
  50% {
    transform: translateY(-10px);
    animation-timing-function: cubic-bezier(0, 0, 0.2, 1);
  }
}`)}\n\n**How it works:**\n- Uses \`translateY\` for GPU-accelerated animation\n- Different timing functions for natural feel\n- Add \`infinite\` for continuous bouncing`,

  'fade': async () => `Here's a fade effect:\n\n${ResponseFormatter.formatCSSCode(`.fade-in {
  opacity: 0;
  animation: fadeIn 0.5s ease-out forwards;
}

@keyframes fadeIn {
  from { opacity: 0; }
  to { opacity: 1; }
}

/* Also available: .fade-out */`)}\n\n**Usage:** Add the class to any element that should fade in on page load.`,

  'button': async () => `Here's a modern button component:\n\n${ResponseFormatter.formatCSSCode(`.btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  padding: 0.75rem 1.5rem;
  font-size: 1rem;
  font-weight: 500;
  border-radius: 0.5rem;
  border: none;
  cursor: pointer;
  transition: all 0.2s ease;
}

.btn--primary {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
}

.btn:hover {
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(102, 126, 234, 0.4);
}

.btn:focus-visible {
  outline: 2px solid #667eea;
  outline-offset: 2px;
}`)}\n\n**Features:** Gradient background, hover lift effect, accessible focus state.`,

  'gradient': async () => `Here's a gradient text effect:\n\n${ResponseFormatter.formatCSSCode(`.gradient-text {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 50%, #f093fb 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}

/* Animated gradient */
.gradient-text--animated {
  background-size: 200% auto;
  animation: gradientShift 3s linear infinite;
}

@keyframes gradientShift {
  0% { background-position: 0% center; }
  100% { background-position: 200% center; }
}`)}\n\n**Note:** Uses \`-webkit-background-clip\` for Safari support.`,

  'card': async () => `Here's an elevated card component:\n\n${ResponseFormatter.formatCSSCode(`.card {
  background: white;
  border-radius: 1rem;
  padding: 1.5rem;
  box-shadow:
    0 4px 6px -1px rgba(0, 0, 0, 0.1),
    0 2px 4px -2px rgba(0, 0, 0, 0.1);
  transition: transform 0.3s ease, box-shadow 0.3s ease;
}

.card:hover {
  transform: translateY(-4px);
  box-shadow:
    0 20px 25px -5px rgba(0, 0, 0, 0.1),
    0 8px 10px -6px rgba(0, 0, 0, 0.1);
}`)}\n\n**Design:** Uses layered shadows for depth. Hover increases elevation.`,

  'default': async () => `I can help you with CSS! Here's what I can do:

**🎨 Generate CSS**
- "Create a bounce animation"
- "Make a gradient button"
- "Design a card component"

**📖 Explain Code**
- "Explain this flexbox layout"
- "What does this animation do?"

**✨ Improve Code**
- "Optimize this CSS"
- "Make this more accessible"

**🔄 Convert**
- "Convert this to Tailwind"
- "Convert to styled-components"

What would you like help with?`
};

/**
 * Mock AI Service for development/demo
 */
export class MockAIService {
  private config: AIServiceConfig;

  constructor(config: Partial<AIServiceConfig> = {}) {
    this.config = { ...DEFAULT_CONFIG, ...config };
  }

  /**
   * Generate mock response based on input
   */
  private getMockResponse(input: string): () => Promise<string> {
    const lowerInput = input.toLowerCase();
    
    // Pattern matching for responses
    if (lowerInput.includes('bounce') || lowerInput.includes('jump')) {
      return MOCK_RESPONSES['bounce'];
    }
    if (lowerInput.includes('fade') || lowerInput.includes('opacity')) {
      return MOCK_RESPONSES['fade'];
    }
    if (lowerInput.includes('button') || lowerInput.includes('btn')) {
      return MOCK_RESPONSES['button'];
    }
    if (lowerInput.includes('gradient')) {
      return MOCK_RESPONSES['gradient'];
    }
    if (lowerInput.includes('card')) {
      return MOCK_RESPONSES['card'];
    }
    
    return MOCK_RESPONSES['default'];
  }

  /**
   * Process request and generate response
   */
  async processRequest(request: AIRequest): Promise<AIMessage> {
    const mockResponseFn = this.getMockResponse(request.prompt);
    const content = await mockResponseFn();

    return {
      role: 'assistant',
      content,
      timestamp: new Date()
    };
  }

  /**
   * Generate CSS effect
   */
  async generateEffect(description: string): Promise<AIGeneratedEffect> {
    const response = await this.processRequest({
      prompt: description,
      context: 'effect'
    });

    const cssCode = ResponseFormatter.extractCodeBlocks(response.content)[0] || '';

    return {
      name: this.generateName(description),
      css: cssCode,
      explanation: response.content.split('```')[2]?.trim() || 'Generated CSS effect',
      tailwind: this.convertToTailwindHint(cssCode)
    };
  }

  /**
   * Stream response for real-time display
   */
  async *streamResponse(input: string): AsyncGenerator<string> {
    const response = await this.processRequest({ prompt: input });
    const words = response.content.split(' ');
    
    for (let i = 0; i < words.length; i++) {
      yield words[i] + (i < words.length - 1 ? ' ' : '');
      await new Promise(r => setTimeout(r, 30));
    }
  }

  /**
   * Generate a class name from description
   */
  private generateName(description: string): string {
    return description
      .toLowerCase()
      .replace(/[^a-z0-9\s]/g, '')
      .split(' ')
      .slice(0, 3)
      .join('-')
      || 'generated-effect';
  }

  /**
   * Simple Tailwind conversion hint
   */
  private convertToTailwindHint(css: string): string | undefined {
    const hints: string[] = [];
    
    if (css.includes('flex')) hints.push('flex');
    if (css.includes('hidden') || css.includes('opacity: 0')) hints.push('opacity-0');
    if (css.includes('rounded')) hints.push('rounded-lg');
    if (css.includes('transition')) hints.push('transition-all');
    if (css.includes('hover')) hints.push('hover:*');
    
    return hints.length > 0 ? `class="${hints.join(' ')}"` : undefined;
  }
}

/**
 * Main AI Service class
 * Provides unified interface for AI operations
 */
export class RoyAIService {
  private config: AIServiceConfig;
  private mockService: MockAIService;

  constructor(config: Partial<AIServiceConfig> = {}) {
    this.config = { ...DEFAULT_CONFIG, ...config };
    this.mockService = new MockAIService(this.config);
  }

  /**
   * Get current configuration
   */
  getConfig(): Readonly<AIServiceConfig> {
    return { ...this.config };
  }

  /**
   * Update configuration
   */
  updateConfig(updates: Partial<AIServiceConfig>): void {
    this.config = { ...this.config, ...updates };
    this.mockService = new MockAIService(this.config);
  }

  /**
   * Process chat message
   */
  async chat(message: string, context?: AIRequest['context']): Promise<AIMessage> {
    return this.mockService.processRequest({ prompt: message, context });
  }

  /**
   * Generate CSS effect
   */
  async generateEffect(description: string): Promise<AIGeneratedEffect> {
    return this.mockService.generateEffect(description);
  }

  /**
   * Stream chat response
   */
  async *streamChat(message: string): AsyncGenerator<string> {
    yield* this.mockService.streamResponse(message);
  }

  /**
   * Explain CSS code
   */
  async explainCSS(code: string): Promise<CSSExplanation> {
    // Mock explanation
    return {
      summary: 'This CSS creates visual styling effects.',
      properties: [
        {
          property: 'animation',
          value: code.match(/animation:\s*([^;]+)/)?.[1] || 'defined',
          explanation: 'Controls the animation behavior',
          browserSupport: 'Modern browsers',
          alternatives: ['transition']
        }
      ],
      tips: [
        'Consider using will-change for better performance',
        'Test animations with prefers-reduced-motion'
      ]
    };
  }

  /**
   * Convert CSS to Tailwind classes
   */
  async cssToTailwind(css: string): Promise<TailwindClasses> {
    const classes: string[] = [];
    
    // Simple conversions
    if (/display:\s*flex/.test(css)) classes.push('flex');
    if (/justify-content:\s*center/.test(css)) classes.push('justify-center');
    if (/align-items:\s*center/.test(css)) classes.push('items-center');
    if (/padding:\s*(\d+)px/.test(css)) {
      const match = css.match(/padding:\s*(\d+)px/);
      classes.push(`p-[${match?.[1]}px]`);
    }
    if (/border-radius/.test(css)) classes.push('rounded-lg');
    if (/transition/.test(css)) classes.push('transition-all');

    return {
      classes: classes.join(' ') || '/* Manual conversion needed */',
      notes: classes.length > 0 
        ? ['Some properties may need custom values'] 
        : ['Complex CSS requires manual conversion'],
      htmlExample: `<div class="${classes.join(' ')}">...</div>`
    };
  }

  /**
   * Check if service is ready
   */
  isReady(): boolean {
    return true; // Mock service is always ready
  }

  /**
   * Get service status
   */
  getStatus(): { provider: string; ready: boolean; latency: number } {
    return {
      provider: this.config.provider,
      ready: this.isReady(),
      latency: Math.random() * 100 + 50 // Simulated latency
    };
  }
}

// Singleton instance
let serviceInstance: RoyAIService | null = null;

/**
 * Get or create AI service instance
 */
export function getRoyAIService(config?: Partial<AIServiceConfig>): RoyAIService {
  if (!serviceInstance) {
    serviceInstance = new RoyAIService(config);
  } else if (config) {
    serviceInstance.updateConfig(config);
  }
  
  return serviceInstance;
}

/**
 * Reset service instance (for testing)
 */
export function resetRoyAIService(): void {
  serviceInstance = null;
}

// Re-exports
export { MockAIService, ResponseFormatter };
export default RoyAIService;
